### ISSUE TITLE
wp dotenv init

### ISSUE THREAD

**Issue by VaLeXaR** [aaemnnosttv/wp-cli-dotenv-command#12] opened 2017-01-19 10:07 UTC
When I try to create .env file from .env.example with command `wp dotenv init --template=.env.example --with-salts`, I see error `Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `localhost`. This could mean your host’s database server is down.`.

Also, if I want to change env variable on `wp dotenv set WP_ENV stading`, appearing error
`PHP Warning:  mysqli_real_connect(): (HY000/1045): Access denied for user 'database_user'@'localhost' (using password: YES) in /srv/www/itua.com.ua/releases/2/web/wp/wp-includes/wp-db.php on line 1538
Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'database_user'@'localhost' (using password: YES) in /srv/www/itua.com.ua/releases/2/web/wp/wp-includes/wp-db.php on line 1538
Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `localhost`. This could mean your host’s database server is down.`

 Why `dotenv` checking connection with database if I want just create or change .env file?

**Comment by aaemnnosttv** [comment] 2017-01-19 10:15
That is rather strange, as the dotenv command is designed to run before WP loads, so this should not come up as an error.

It sounds like the `dotenv` package is not installed correctly or missing.

Try changing in to a directory where you are certain WordPress is installed and available and run `wp` to see if `dotenv` appears in the list of available sub commands.

If it's not there, then what's happening is that WP-CLI is trying to load all other commands as it would normally to run after WP is loaded, hence the error you're seeing.

The proper way to install the package is like so:

```
wp package install aaemnnosttv/wp-cli-dotenv-command:^1.0
```

You can also use this command to re-install the package.

**Comment by VaLeXaR** [comment] 2017-01-19 10:33
Thanks for quick answer.
`dotenv` command is available on `wp`

But if in .env file exist not correct database connection `wp dotenv set WP_ENV stading` not working. Why?

**Comment by aaemnnosttv** [comment] 2017-01-22 10:28
Did you try re-installing the package with the latest version using the recommended method?

I cannot reproduce the problem you are having as the `dotenv` command does not rely on WordPress loading at all.  It can be run anywhere on the filesystem, without WordPress, and without a database.

Like I said, it sounds like the command is somehow not installed correctly. The commands you are issuing are correct, so this issue is specific to your environment.

If you're still having trouble, please provide me with the following so I can investigate further

- Output of `wp --info`
- Output of `composer show -d="$HOME/.wp-cli/packages/"`  
Where the path in `-d` should match the packages directory shown in the output of `wp --info` at `WP-CLI packages dir`. The command shown will match the default directory.
- Output of `wp help dotenv`

**Comment by aaemnnosttv** [comment] 2017-05-05 20:02
Closing this out until there is more information to investigate.

**Closed as completed by aaemnnosttv** 2017-05-05 20:02 UTC
Labels: unconfirmed

**Comment by dweipert-3138720606** [comment] 2017-05-29 16:03
I have a boilerplate project with `"aaemnnosttv/wp-cli-dotenv-command": "^1.0",` as dependency in its composer.json.
When using  `composer create-project` it's installing it, and the command `wp dotenv` is available.
But when calling `wp dotenv init` or `wp help dotenv` I get
```
Error: The site you have requested is not installed.
Run `wp core install`.
```
Dunno if that's normal for all commands, even when they don't rely on wp being there, but seems like it.

After installing `wp help dotenv` is working, but `wp dotenv init` yields
```
Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at ``. This could mean your host’s database server is down.
```

According to `wp --info` the `$HOME/.wp-cli/packages/` dir doesn't exist.

Only after installing it via `wp package install aaemnnosttv/wp-cli-dotenv-command:^1.0` I can use it without the previous error and `$HOME/.wp-cli/packages/` exists now.

The only way around that I see right now, atleast for my case, is
```
"scripts": {
    "post-create-project-cmd": [
      "wp package install aaemnnosttv/wp-cli-dotenv-command:^1.0"
    ]
  }
```

**Comment by aaemnnosttv** [comment] 2017-05-29 17:52
The command should be installed using the `wp package install` rather than required in at the project level. Is there a reason you don't want to install it that way?

**Comment by dweipert-3138720606** [comment] 2017-05-30 07:06
No, it's just that I thought requireing should work, because it's basically just another composer package. But putting it in `post-create-project-cmd` is also fine.

**Comment by ethanclevenger91** [comment] 2022-04-22 18:55
If you're going to require a WP-CLI package via Composer at the project level, WP-CLI itself has to be required via Composer and you have to run that copy.

So:

```composer require wp-cli/wp-cli-bundle aaemnnosttv/wp-cli-dotenv-command```

And then refer to the binary included by that:

```vendor/bin/wp dotenv salts generate```

Should work.

**Comment by ethanclevenger91** [comment] 2022-04-28 02:24
Forget my last comment. Simpler solution.

First, the cause: WP-CLI, installed globally, won't run your project's Composer autoloader until WordPress itself has loaded (assuming your WordPress loading logic has been tweaked to include the Composer autoloader). It will load the global Composer's autoloader, assuming you installed WP-CLI globally via Composer, but it has no logic to load your project's autoloader (because a vanilla WordPress install wouldn't have that).

If you want to include your project's autoloader no matter what WP-CLI you're using, use the `require` config in your project's `wp-cli.yml` file:

```
require:
  - vendor/autoload.php
```
